title: Parchment
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://rahul-bothra.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "hbbblog"
   link: "www.hbbblog.k-r.pw"
 - name: "hbbblog"
   absolute-link: "www.hbbblog.k-r.pw"
