title: Blog de Fernanda Carvajal  
author: Fernanda Carvajal Gómez
subtitle: Apuntes de un tanuki 

url: "https://facarvajalg.github.io"
baseurl: "https://facarvajalg.github.io"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "https://facarvajalg.github.io/about/"
 - name: "Resume"
   absolute-link: https://www.linkedin.com/in/fcarvajalg/"
